site_name: RemaLab WMS
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Karanlık Moda Geç
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Aydınlık Moda Geç
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
nav:
  - Ana Sayfa: index.md
  - API Referansı: api_reference.md
